### ISSUE TITLE
Wire Diagram / schematic

### ISSUE THREAD

**Issue by kefkevm** [djgreeb/Sampler-DJS-500#3]
Hi,

Do you have a wire diagram or electric schamatic?

greetz

**Comment by djgreeb** [comment]
Hi!
There is no finished circuit so that I can publish it. Maybe later I will find time and draw up a diagram. In the meantime, you can define the connection points for the pads, buttons, and encoder in the CubeMx project or in the Firmware/Sampler/F7.pdf file. Signal names correspond to connected buttons and LEDs.

[https://github.com/djgreeb/Sampler-DJS-500/blob/main/Firmware/Sampler/F7.pdf](url)
